---
env_id: CartPole-v0
env_path:
env_settings:
  something:
  even_more: 
train: false
discount_factor: 0.99
clip_eps: 0.2
lr_actor: 0.0003
lr_critic: 0.001
lr_discriminator: 0.001
train_steps: 100000
max_episode_len: 400
update_steps: 1600
checkpoint_steps: 1600
num_epochs: 40
num_d_epochs: 2
seed: 42
